### ISSUE TITLE
Bessere Titel für "Bedeutungsabfrage" und Controllernamen (app.js)

### ISSUE THREAD

**Issue by ghost** [MBredehorn/ChineseApp#4]
-z.B in App.js (angular) manchmal deutsch aber auch englische Namen
-Linknamen auf der Oberfläche!! z.B. : "Bedeutungsabfrage" (klingt dämlich)
-Kommentare in Englisch oder Deutsch?

**Comment by Georg-W** [comment]
Vorschlag: 
Namen und Funktionen in englisch
Camelcase (Anfang immer klein) 
Kommentare auf englisch
angular directives mit "my"- prefix
